env:
  - NODEJS_VER=12.16.2

language: node_js
node_js: $NODEJS_VER
warnings_are_errors: false

jobs:
  include:
    - stage: Master-Push
      if: branch = master AND type = push
      script:
        - pyenv global 3.7.1
        - pip install -U pip
        - pip install awscli
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        - echo "CI/CD Starting for $BRANCH"
        - npm install
        - CI=false npm run build
        - npm run deploy
      after_success:
        - echo "Deployed Successfully"

    - stage: Master-PR
      if: branch = master AND type = pull_request
      script:
        - echo "CI/CD Starting for $BRANCH"
        - npm install
        - CI=false npm run build
      after_success:
        - echo "CI Successfully"

    - stage: Dev-Push
      if: branch = dev AND type = push
      script:
        - echo "CI/CD Starting for $BRANCH"
        - npm install
        - CI=false npm run build
      after_success:
        - echo "CI Successfully"